ARG JUPYTERHUB_VERSION

FROM jupyterhub/singleuser:$JUPYTERHUB_VERSION

USER root

RUN apt-get update && apt-get install -y\
    git\
 && rm -rf /var/lib/apt/lists/*

USER jovyan

RUN python3 -m pip install --no-cache\
    cdsdashboards[user]==0.1.0\
    ipywidgets==7.5.1\
    voila==0.1.21\
    numpy==1.19.0\
    pandas==1.0.5\
    numba==0.50.1\
    matplotlib==3.3.0\
    scipy==1.5.1\
    statsmodels==0.11.1\
    scikit-learn==0.23.1\
    dash==1.13.4\
    panel==0.9.7\
    jupyterlab-git==0.20.0\
    jupyterlab-latex==2.0.0\
    bqplot\
    jupyter-dash\
    jupyterlab-sql

RUN jupyter labextension install\
    @jupyterlab/toc\
    @jupyterlab/git\
    @jupyterlab/latex\
    @jupyter-widgets/jupyterlab-manager\
    @jupyter-voila/jupyterlab-preview\
    jupyterlab-dash\
    jupyerlab-spreadsheet\
    bqplot\
    @karosc/jupyterlab_dracula\
    jupyterlab-theme-solarized-dark
